services:
  streamimdb-addon:
    build: .
    container_name: streamimdb-addon
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: "7000"
      SERVER_URL: "http://localhost:7001"
    ports:
      - "7001:7000"
